apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: geoloc-ecr-eks-app
  name: geoloc-ecr-eks-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: geoloc-ecr-eks-app
  template:
    metadata:
      labels:
        app: geoloc-ecr-eks-app
    spec:
      containers:
      - name: my-geoloc-ecr-eks-app
        image: 358966077154.dkr.ecr.us-east-1.amazonaws.com/geo_ecr_helm_repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082


# service type loadbalancer
--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: geoloc-ecr-eks-app
    k8s-app: geoloc-ecr-eks-app
  name: geoloc-ecr-eks-app
spec:
  selector:
    app: geoloc-ecr-eks-app
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8082
  type: LoadBalancer 

